run:
  concurrency: 4
  timeout: 1m
  issues-exit-code: 1
  tests: false
  build-tags:
    - gosec
    - scopelint
    - stylecheck
    - gocritic
    - unconvert
    - goconst
    - dupl
    - unparam
    - dogsled
  skip-dirs:
    - deployment
    - examples
    - goutls
    - ppro
    - pproto
    - xsd
  skip-dirs-use-default: true
  skip-files:
    - Makefile
linters-settings:
  dogsled:
    max-blank-identifiers: 2
  dupl:
    threshold: 100
  errcheck:
    check-type-assertions: false
    check-blank: false
  gocognit:
    min-complexity: 10
  goconst:
    min-len: 3
    min-occurrences: 2
  gocritic:
    enabled-tags:
      - performance
    settings:
      captLocal:
        paramsOnly: true
      rangeValCopy:
        sizeThreshold: 32
  gocyclo:
    min-complexity: 10
  gofmt:
    simplify: true
  golint:
    min-confidence: 0.8 # minimal confidence for issues
  govet:
    check-shadowing: true
    settings:
      printf: # analyzer name, run `go tool vet help` to see all analyzers
        funcs: # run `go tool vet help printf` to see available settings for `printf` analyzer
          - (github.com/golangci/golangci-lint/pkg/logutils.Log).Infof
          - (github.com/golangci/golangci-lint/pkg/logutils.Log).Warnf
          - (github.com/golangci/golangci-lint/pkg/logutils.Log).Errorf
          - (github.com/golangci/golangci-lint/pkg/logutils.Log).Fatalf
    enable:
      - atomic
    enable-all: false
    disable-all: false
  depguard:
    list-type: blacklist
    include-go-root: false
    packages:
      - github.com/sirupsen/logrus
    packages-with-error-message:
      - github.com/sirupsen/logrus: "logging is allowed only by logutils.Log"
  maligned:
    # print struct with more effective memory layout or not, false by default
    suggest-new: true
  nakedret:
    max-func-lines: 30
  prealloc:
    simple: true
    range-loops: true
    for-loops: false
  rowserrcheck:
    packages:
      - github.com/jmoiron/sqlx
  unparam:
    check-exported: false
  unused:
    check-exported: false
linters:
  enable:
    - megacheck
    - govet
  disable:
    - maligned
    - prealloc
  disable-all: false
  presets:
    - bugs
    - unused
  fast: false
issues:
  exclude:
    - abcdef
  exclude-rules:
    - path: _test\.go
      linters:
        - gocyclo
        - errcheck
        - dupl
        - gosec
    - linters:
        - lll
      source: "^//go:generate "
    - linters:
        - staticcheck
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
  new: false
