name: Tests
on:
  pull_request:
  push:
    tags:
    - v*
    branches:
    - master
    - main
    - "releases/*"
jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: golangci/golangci-lint-action@v2
      name: golangci-lint
      with:
        version: latest
  test:
    strategy:
      matrix:
        go-version: [1.16.x]
        platform: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
    - uses: actions/setup-go@v1
      name: prepare
      with:
        go-version: ${{ matrix.go-version }}
    - uses: actions/checkout@v1
    - name: test
      env:
        GO111MODULE: on
      run: go test -cover .
